#!/usr/bin/python
"""

Major (required) commands are:

  action to take
  -e / --environment -- environment to affect


up: Creates (if necessary), configures, and deploys a complete environment, including uploading static files. (local uploads to same static file server as staging)
hfu up -e local
hfu up -e staging
hfu up -e prod (For production, does test, then ups prod.)
hfu up -e test

manage: Allows you to run manage.py commands in a particular environment
hfu manage -e local -o [ createdb / syncdb / migrate / etc. ]
hfu manage -e staging -o [ createdb / syncdb / migrate / etc. ]
hfu manage -e prod -o [ createdb / syncdb / migrate / etc. ]
hfu manage -e test -o [ createdb / syncdb / migrate / etc. ]

destroy: Use with caution. Destorys an environment, good for keeping you from being charged for it.
hfu destroy -e local
hfu destroy -e staging
hfu destroy -e prod
hfu destroy -e test

test: Runs your test suite
hfu test (ups test, runs test)

reset: Destroys and then ups an environment.
hfu reset -e local
hfu reset -e staging
hfu reset -e prod
hfu reset -e test

revert: Revert to the state prior to the most recent "up." Does not apply to local.
hfu revert -e staging
hfu revert -e prod
hfu revert -e test

"""

import os
import sys
import uuid
import os.path
import argparse
import StringIO
import subprocess
import ConfigParser


actions = ('up', 'manage', 'destroy', 'reset', 'test', 'revert')
environments = ('local', 'staging', 'prod', 'test')
config_dir = "hfu_settings"


def run_command(command):
    print('\nRUNNING: %s' % command)
    output = []
    process = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    while True:
        nextline = process.stdout.readline()
        if (nextline == '') and (process.poll() is not None):
            break
        output.append(nextline)
        sys.stdout.write(nextline)
        sys.stdout.flush()

    exitcode = process.returncode
    if exitcode != 0:
        print('ERROR: Command <%s> got returncode %s' % (command, exitcode))
        sys.exit(100)
    return "".join(output)


def parse_commandline(args):
    parser = argparse.ArgumentParser(description="Heroku Fu -- utilities to demonstate your heroku fu.")
    parser.add_argument('action', help="What action to take. up, manage, destroy, or reset.")
    parser.add_argument('-e', '--environment')
    parser.add_argument('-o', '--options')
    input = parser.parse_args(args)
    if input.action not in actions:
        print('You must pick an action of either up, manage, destroy, test, or reset')
        sys.exit(10)
    if (input.environment not in environments) and (input.action.upper() != 'TEST'):
        print('you must pick an environment of local, staging, prod, or test.')
        sys.exit(10)
    if input.options and input.action != "manage":
        print('You only use the --options argument when running "hfu manage."')
        sys.exit(10)
    if input.action == "manage" and input.options is None:
        print('You must use the --options argument when running "hfu manage" to tell manage.py what to do.')
        sys.exit(10)
    return (input.action, input.environment, input.options)


def verify_local_environment():
    # Get current directory
    CWD = os.getcwd()

    # Get updates if any
    run_command('git pull -u')

    # Verify git
    git_dir = os.path.join(CWD, '.git')
    if not os.path.isdir(git_dir):
        print('ERROR: You need to execute this from your project folder. Your project folder must be a git repo.')
        sys.exit(100)
    # Verify Vagrant
    if not os.path.isfile(os.path.join(CWD, 'Vagrantfile')):
        print('ERROR: You need to execute this from your project folder. Your project folder must contain a Vagrantfile.')
        sys.exit(100)


def heroku_create_app(appname):
    run_command('heroku create --remote %s' % appname)
    run_command('heroku apps:rename --remote %s %s' % (appname, appname))


def heroku_add_addon(appname, addon):
    run_command('heroku addons:add %s --app %s' % (addon, appname))


def heroku_get_db_url(appname):
    return run_command('heroku config:get DATABASE_URL --app %s' % appname).strip()


def heroku_get_db_name(appname):
    output = run_command('heroku pg --app %s' % appname)
    for line in output.split('\n'):
        if '===' in line:
            return line.strip('=').split('(')[0].strip()


def heroku_set_config(file_list, appname):
    config_list = []
    for filename in file_list:
        with open(os.path.join(config_dir, filename), 'r') as fileobj:
            config_list.extend([x.strip() for x in fileobj.readlines()])
    for config_pair in config_list:
        key, value = config_pair.split('=')
        result = run_command('heroku config:get %s --app %s' % (key, appname)).strip()
        if result != value:
            run_command('heroku config:set %s --app %s' % (config_pair, appname))


def get_config_value(config_file, config_key):
    dummy_section_name = "dummysection"
    config_text = StringIO.StringIO()
    config_text.write('[%s]\n' % dummy_section_name)
    config_text.write(open(os.path.join(config_dir, config_file), 'rt').read())
    config_text.seek(0, os.SEEK_SET)
    config_parsed = ConfigParser.SafeConfigParser()
    config_parsed.readfp(config_text)
    return config_parsed.get(dummy_section_name, config_key)


def grab_database_from_offsite_backup():
    offsitebackup_user = get_config_value('settings_all', 'DB_BACKUP_USER')
    offsitebackup_server = get_config_value('settings_all', 'DB_BACKUP_SERVER')
    offsitebackup_path = get_config_value('settings_all', 'DB_BACKUP_PATH')
    db_backup_name = 'www_database'
    run_command('scp %s@%s:%s/%s* .' % (offsitebackup_user, offsitebackup_server, offsitebackup_path, db_backup_name))
    dir_list = os.listdir(os.getcwd())
    db_file_list = []
    db_target_file = "dump.db"
    chunksize = 8192
    for entry in dir_list:
        if entry.startswith(db_backup_name):
            db_file_list.append(entry)

    with open(db_target_file, 'wb') as dbtarget:
        for db_source_file in db_file_list:
            with open(db_source_file, 'rb') as dbsource:
                while True:
                    chunk = dbsource.read(chunksize)
                    if chunk:
                        dbtarget.write(chunk)
                    else:
                        break

    for db_source_file in db_file_list:
        os.remove(db_source_file)


def heroku_up_environment(appname, desired_addons, dynos_web, database_type):
    # Load app names
    test_app_name = get_config_value('settings_test', 'HEROKU_APP_NAME')
    prod_app_name = get_config_value('settings_prod', 'HEROKU_APP_NAME')
    staging_app_name = get_config_value('settings_staging', 'HEROKU_APP_NAME')

    # Create Heroku app if needed
    current_app_list = run_command('heroku apps')
    if appname not in current_app_list:
        heroku_create_app(appname)

    # Load settings
    if appname == prod_app_name:
        heroku_set_config(['settings_all', 'settings_auth_prod', 'settings_prod'], appname)
    elif appname == staging_app_name:
        heroku_set_config(['settings_all', 'settings_auth_staging', 'settings_staging'], appname)
    elif appname == test_app_name:
        heroku_set_config(['settings_all', 'settings_auth_test', 'settings_test'], appname)
    else:
        raise NotImplementedError

    # Load desired addons
    current_addons = run_command('heroku apps:info --app %s' % appname)
    for addon in desired_addons:
        if addon not in current_addons:
            heroku_add_addon(appname, addon)

    # Create DB if one does not exist
    current_db_list = run_command('heroku pg --app %s' % appname)
    if "===" not in current_db_list:
        run_command('heroku addons:add %s --app %s' % (database_type, appname))

    # If doing staging or test, restore DB from prod.
    if (appname == staging_app_name) or (appname == test_app_name):
        grab_database_from_offsite_backup()
        public_db_file_name = str(uuid.uuid4()) + '.hfu-db'  # Don't want a predictable file name; this will be public
        heroku_db_name = heroku_get_db_name(appname)
        run_command('s3cmd put dump.db s3://%s/%s' % (get_config_value('settings_staging', 'S3_BUCKET_NAME'), public_db_file_name))
        run_command('s3cmd setacl s3://%s/%s --acl-public' % (get_config_value('settings_staging', 'S3_BUCKET_NAME'), public_db_file_name))
        run_command("heroku pgbackups:restore %s 'https://s3.amazonaws.com/%s/%s' --app %s --confirm %s"
                    % (heroku_db_name, get_config_value('settings_staging', 'S3_BUCKET_NAME'), public_db_file_name, appname, appname))
        run_command('s3cmd del s3://%s/*.hfu-db' % (get_config_value('settings_staging', 'S3_BUCKET_NAME')))

    run_command('git push %s master' % appname)
    run_command('heroku pg:wait --app %s' % appname)
    run_command('heroku ps:scale web=%s --app %s' % (dynos_web, appname))


def log_deploy(environment):
    pass
    # git_shortlog = run_command('git log -n1 --oneline')
    # git_longlog = run_command('git log -n3 --oneline')

    # config_file = "hfu_settings/settings_" + environment
    # with open(config_file, 'rt') as fileobj:
    #     for line in fileobj:
    #         line = line.strip()
    #         if line.startswith('NEW_RELIC_APP_NAME'):
    #             APP_NAME = line.split('=')[1]
    #         elif line.startswith('NEW_RELIC_LICENSE_KEY'):
    #             API_KEY = line.split('=')[1]
    # run_command('curl -H "x-api-key:%s" -d "deployment[app_name]=%s" -d "deployment[description]=%s" -d "deployment[changelog]=%s" https://rpm.newrelic.com/deployments.xml'
    #             % (API_KEY, APP_NAME, git_shortlog, git_longlog))


def up_command(environment):
    verify_local_environment()
    CWD = os.getcwd()
    sys.path.append(CWD)

    if environment == "local":
        # Get a copy of the production DB here:
        prod_app_name = get_config_value('settings_prod', 'HEROKU_APP_NAME')
        grab_database_from_offsite_backup()

        run_command('vagrant plugin list | grep -q "vagrant-vbguest" || vagrant plugin install vagrant-vbguest  ')
        if os.path.isfile(os.path.join(CWD, '.vagrant/machines/default/virtualbox/id')):
            # Virtual machine exists
            run_command('vagrant reload')
            run_command('vagrant provision')
        else:
            # Virtual machine does not exist
            run_command('vagrant up')
            run_command('vagrant provision')
        collectstatic(environment)

    elif environment == 'prod':
        test_command()
        import hfu_settings.herokuconfig_prod as hsettings
        prod_app_name = get_config_value('settings_prod', 'HEROKU_APP_NAME')
        heroku_up_environment(prod_app_name, hsettings.desired_addons, hsettings.dynos_web, hsettings.database_type)
        log_deploy(environment)
        collectstatic(environment)

    elif environment == 'staging':
        import hfu_settings.herokuconfig_staging as hsettings
        staging_app_name = get_config_value('settings_staging', 'HEROKU_APP_NAME')
        heroku_up_environment(staging_app_name, hsettings.desired_addons, hsettings.dynos_web, hsettings.database_type)
        log_deploy(environment)
        collectstatic(environment)

    elif environment == 'test':
        log_deploy(environment)
        import hfu_settings.herokuconfig_test as hsettings
        test_app_name = get_config_value('settings_test', 'HEROKU_APP_NAME')
        heroku_up_environment(test_app_name, hsettings.desired_addons, hsettings.dynos_web, hsettings.database_type)
        log_deploy(environment)
        collectstatic(environment)
    else:
        raise NotImplementedError


def manage_command(environment, options):
    verify_local_environment()
    if environment == "local":
        run_command('vagrant ssh -c "/vagrant/devserver/manage_local.bash %s"' % options)

    elif environment == 'prod':
        run_command('heroku run python manage.py %s --app %s' % (options, prod_app_name))

    elif environment == 'staging':
        run_command('heroku run python manage.py %s --app %s' % (options, staging_app_name))

    elif environment == 'test':
        run_command('heroku run python manage.py %s --app %s' % (options, test_app_name))
    else:
        raise NotImplementedError


def collectstatic(environment):
    run_command('vagrant ssh -c "/vagrant/devserver/collectstatic.bash %s"' % environment)


def heroku_destroy_app(appname):
    run_command('heroku apps:destroy --app %s --confirm %s' % (appname, appname))


def destroy_command(environment):
    verify_local_environment()
    if environment == "local":
        run_command('vagrant destroy -f')
    elif environment == "prod":
        print('')
        print('')
        print('BIG FREAKING WARNING: If you continue, the PRODUCTION environment will be destroyed!')
        print('This will take down the production environment. It will not serve requests until it is rebuilt.')
        print('In addtion, this will DELETE THE PRODUCTION DATABASE which will require that you restore from backup.')
        print('If the backup is not recent, you will lose data. You may lose data anyway.')
        print('It will also delete the Redis DB which contains split-testing info.')
        print('YOU ALMOST CERTAINLY SHOULD NOT DO THIS.')
        print('')
        print('At the following prompt, type (all caps) "DESTROY PRODUCTION" and hit ENTER to continue, or anything else to quit.')
        verify = raw_input('Verify destruction of production: ')
        print('')
        if verify == "DESTROY PRODUCTION":
            heroku_destroy_app(prod_app_name)
        else:
            print('Will not destroy production. Quitting.')
            sys.exit(0)
    elif environment == "staging":
        heroku_destroy_app(staging_app_name)
    elif environment == "test":
        heroku_destroy_app(test_app_name)
    else:
        raise NotImplementedError


def vagrant_command(command):
    run_command('vagrant ssh -c "%s"' % command)


def test_command():
    up_command('test')
    vagrant_command('/bin/bash /vagrant/devserver/run_tests.bash')


def revert_command(environment):
    if environment == "prod":
        appname = prod_app_name
    elif environment == "test":
        appname = test_app_name
    elif environment == 'staging':
        appname = staging_app_name
    else:
        raise NotImplementedError
    run_command('heroku rollback --app %s' % appname)


def reset_command(environment):
    destroy_command(environment)
    up_command(environment)


def main(args):
    action, environment, options = parse_commandline(args)

    if action == 'up':
        up_command(environment)
    elif action == 'manage':
        manage_command(environment, options)
    elif action == 'destroy':
        destroy_command(environment)
    elif action == 'test':
        test_command()
    elif action == 'reset':
        reset_command(environment)
    elif action == "revert":
        revert_command(environment)
    else:
        print('ERROR: Command line incorrect.')
        print(__doc__)
        sys.exit(10)


if __name__ == '__main__':
    main(sys.argv[1:])
